### ISSUE TITLE
Double entries in drop down menu

### ISSUE THREAD

**Issue by anticapitalista** [TheNiteCoder/system-keyboard-qt#9]
Hi!

I attach an image of the double entries. This is on antiX bullseye (testing). Also no up/down arrows.

![double_entries](https://user-images.githubusercontent.com/419094/102621036-ae702280-4147-11eb-8704-2fb7f5241326.png)

![no_arrows](https://user-images.githubusercontent.com/419094/102621501-54bc2800-4148-11eb-9705-4e583b5f6004.jpg)

**Comment by TheNiteCoder** [comment]
This is now fixed with bf21c9fe820676e26bf0a809952e88af17655d37
